name: main
on:
  push:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/test
        name: Trigger triggered
        with:
          ref: test
          file: triggered.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
