name: triggered
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context
        env:
          TEST_REF: ${{ github.ref_name }}
        run: |
          [[ "${TEST_REF}" != "test" ]] && exit 22 || echo "success"